import { Provider } from "jotai";
import "./globals.css";
import { Suspense } from "react";
 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <Provider>
        <body>
          <Suspense fallback="wait...">{children}</Suspense>
        </body>
      </Provider>
    </html>
  );
}
